# Generated by Django 5.2.8 on 2026-05-10 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderFollowOthers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(max_length=50)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.PositiveBigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interactive_sp_follow_others',
                'indexes': [models.Index(fields=['actor_id'], name='interactive_actor_i_371a63_idx'), models.Index(fields=['target_id'], name='interactive_target__06de75_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderFollowServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(max_length=50)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.PositiveBigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interactive_sp_follow_sp',
                'indexes': [models.Index(fields=['actor_id'], name='interactive_actor_i_252731_idx'), models.Index(fields=['target_id'], name='interactive_target__ab80ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderFollowUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(max_length=50)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.PositiveBigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interactive_sp_follow_user',
                'indexes': [models.Index(fields=['actor_id'], name='interactive_actor_i_0f48f8_idx'), models.Index(fields=['target_id'], name='interactive_target__e4a447_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderLikeOthers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(max_length=50)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.PositiveBigIntegerField()),
                ('like_status', models.PositiveSmallIntegerField(choices=[(1, 'like'), (2, 'none'), (3, 'dislike')], default=1)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interactive_sp_like_others',
                'indexes': [models.Index(fields=['actor_id'], name='interactive_actor_i_476693_idx'), models.Index(fields=['target_id'], name='interactive_target__506546_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderLikeServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(max_length=50)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.PositiveBigIntegerField()),
                ('like_status', models.PositiveSmallIntegerField(choices=[(1, 'like'), (2, 'none'), (3, 'dislike')], default=1)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interactive_sp_like_sp',
                'indexes': [models.Index(fields=['actor_id'], name='interactive_actor_i_5c79f3_idx'), models.Index(fields=['target_id'], name='interactive_target__9b8d45_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderLikeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(max_length=50)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.PositiveBigIntegerField()),
                ('like_status', models.PositiveSmallIntegerField(choices=[(1, 'like'), (2, 'none'), (3, 'dislike')], default=1)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interactive_sp_like_user',
                'indexes': [models.Index(fields=['actor_id'], name='interactive_actor_i_f1cac0_idx'), models.Index(fields=['target_id'], name='interactive_target__7fb419_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderScoreOthers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(max_length=50)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.PositiveBigIntegerField()),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interactive_sp_score_others',
                'indexes': [models.Index(fields=['actor_id'], name='interactive_actor_i_6a193a_idx'), models.Index(fields=['target_id'], name='interactive_target__9d22f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderScoreServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(max_length=50)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.PositiveBigIntegerField()),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interactive_sp_score_sp',
                'indexes': [models.Index(fields=['actor_id'], name='interactive_actor_i_921d0b_idx'), models.Index(fields=['target_id'], name='interactive_target__5aa0a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderShareOthers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(max_length=50)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.PositiveBigIntegerField()),
                ('platform', models.CharField(max_length=50)),
                ('destination_type', models.CharField(blank=True, max_length=50, null=True)),
                ('destination_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('url', models.URLField(default='')),
                ('reason', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interactive_sp_share_others',
                'indexes': [models.Index(fields=['actor_id'], name='interactive_actor_i_7f515b_idx'), models.Index(fields=['target_id'], name='interactive_target__4e5cc3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderShareServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(max_length=50)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.PositiveBigIntegerField()),
                ('platform', models.CharField(max_length=50)),
                ('destination_type', models.CharField(blank=True, max_length=50, null=True)),
                ('destination_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('url', models.URLField(default='')),
                ('reason', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interactive_sp_share_sp',
                'indexes': [models.Index(fields=['actor_id'], name='interactive_actor_i_71b6ab_idx'), models.Index(fields=['target_id'], name='interactive_target__5a8e0a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderShareUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(max_length=50)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.PositiveBigIntegerField()),
                ('platform', models.CharField(max_length=50)),
                ('destination_type', models.CharField(blank=True, max_length=50, null=True)),
                ('destination_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('url', models.URLField(default='')),
                ('reason', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interactive_sp_share_user',
                'indexes': [models.Index(fields=['actor_id'], name='interactive_actor_i_af3929_idx'), models.Index(fields=['target_id'], name='interactive_target__c26eeb_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserFollowOthers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(max_length=50)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.PositiveBigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interactive_user_follow_others',
                'indexes': [models.Index(fields=['actor_id'], name='interactive_actor_i_33490c_idx'), models.Index(fields=['target_id'], name='interactive_target__41132f_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserFollowServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(max_length=50)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.PositiveBigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interactive_user_follow_service_provider',
                'indexes': [models.Index(fields=['actor_id'], name='interactive_actor_i_aee204_idx'), models.Index(fields=['target_id'], name='interactive_target__3d7367_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserFollowUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(max_length=50)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.PositiveBigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interactive_user_follow_user',
                'indexes': [models.Index(fields=['actor_id'], name='interactive_actor_i_8ff77c_idx'), models.Index(fields=['target_id'], name='interactive_target__f80a22_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserLikeOthers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(max_length=50)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.PositiveBigIntegerField()),
                ('like_status', models.PositiveSmallIntegerField(choices=[(1, 'like'), (2, 'none'), (3, 'dislike')], default=1)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interactive_user_like_others',
                'indexes': [models.Index(fields=['actor_id'], name='interactive_actor_i_9b6af5_idx'), models.Index(fields=['target_id'], name='interactive_target__3b0a6d_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserLikeServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(max_length=50)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.PositiveBigIntegerField()),
                ('like_status', models.PositiveSmallIntegerField(choices=[(1, 'like'), (2, 'none'), (3, 'dislike')], default=1)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interactive_user_like_service_provider',
                'indexes': [models.Index(fields=['actor_id'], name='interactive_actor_i_9ff091_idx'), models.Index(fields=['target_id'], name='interactive_target__0f016a_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserLikeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(max_length=50)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.PositiveBigIntegerField()),
                ('like_status', models.PositiveSmallIntegerField(choices=[(1, 'like'), (2, 'none'), (3, 'dislike')], default=1)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interactive_user_like_user',
                'indexes': [models.Index(fields=['actor_id'], name='interactive_actor_i_c3ae22_idx'), models.Index(fields=['target_id'], name='interactive_target__4f3825_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserScoreOthers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(max_length=50)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.PositiveBigIntegerField()),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interactive_user_score_others',
                'indexes': [models.Index(fields=['actor_id'], name='interactive_actor_i_53ed40_idx'), models.Index(fields=['target_id'], name='interactive_target__767d8d_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserScoreServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(max_length=50)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.PositiveBigIntegerField()),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interactive_user_score_service_provider',
                'indexes': [models.Index(fields=['actor_id'], name='interactive_actor_i_232b31_idx'), models.Index(fields=['target_id'], name='interactive_target__b78dea_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserShareOthers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(max_length=50)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.PositiveBigIntegerField()),
                ('platform', models.CharField(max_length=50)),
                ('destination_type', models.CharField(blank=True, max_length=50, null=True)),
                ('destination_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('url', models.URLField(default='')),
                ('reason', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interactive_user_share_others',
                'indexes': [models.Index(fields=['actor_id'], name='interactive_actor_i_36d9e1_idx'), models.Index(fields=['target_id'], name='interactive_target__279f91_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserShareServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(max_length=50)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.PositiveBigIntegerField()),
                ('platform', models.CharField(max_length=50)),
                ('destination_type', models.CharField(blank=True, max_length=50, null=True)),
                ('destination_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('url', models.URLField(default='')),
                ('reason', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interactive_user_share_service_provider',
                'indexes': [models.Index(fields=['actor_id'], name='interactive_actor_i_cb477a_idx'), models.Index(fields=['target_id'], name='interactive_target__c44a6e_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserShareUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(max_length=50)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.PositiveBigIntegerField()),
                ('platform', models.CharField(max_length=50)),
                ('destination_type', models.CharField(blank=True, max_length=50, null=True)),
                ('destination_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('url', models.URLField(default='')),
                ('reason', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interactive_user_share_user',
                'indexes': [models.Index(fields=['actor_id'], name='interactive_actor_i_242cb1_idx'), models.Index(fields=['target_id'], name='interactive_target__4c15c6_idx')],
            },
        ),
    ]
