# Generated by Django 5.2.8 on 2026-07-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InteractiveOperations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderfollowothers',
            name='actor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business')]),
        ),
        migrations.AlterField(
            model_name='serviceproviderfollowothers',
            name='target_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business'), (5, 'product'), (6, 'service')]),
        ),
        migrations.AlterField(
            model_name='serviceproviderfollowserviceprovider',
            name='actor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business')]),
        ),
        migrations.AlterField(
            model_name='serviceproviderfollowserviceprovider',
            name='target_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business'), (5, 'product'), (6, 'service')]),
        ),
        migrations.AlterField(
            model_name='serviceproviderfollowuser',
            name='actor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business')]),
        ),
        migrations.AlterField(
            model_name='serviceproviderfollowuser',
            name='target_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business'), (5, 'product'), (6, 'service')]),
        ),
        migrations.AlterField(
            model_name='userfollowothers',
            name='actor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business')]),
        ),
        migrations.AlterField(
            model_name='userfollowothers',
            name='target_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business'), (5, 'product'), (6, 'service')]),
        ),
        migrations.AlterField(
            model_name='userfollowserviceprovider',
            name='actor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business')]),
        ),
        migrations.AlterField(
            model_name='userfollowserviceprovider',
            name='target_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business'), (5, 'product'), (6, 'service')]),
        ),
        migrations.AlterField(
            model_name='userfollowuser',
            name='actor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business')]),
        ),
        migrations.AlterField(
            model_name='userfollowuser',
            name='target_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business'), (5, 'product'), (6, 'service')]),
        ),
    ]
