# Generated by Django 5.2.8 on 2026-07-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InteractiveOperations', '0002_alter_serviceproviderfollowothers_actor_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderlikeothers',
            name='actor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business')]),
        ),
        migrations.AlterField(
            model_name='serviceproviderlikeothers',
            name='target_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business'), (5, 'product'), (6, 'service'), (7, 'comment')]),
        ),
        migrations.AlterField(
            model_name='serviceproviderlikeserviceprovider',
            name='actor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business')]),
        ),
        migrations.AlterField(
            model_name='serviceproviderlikeserviceprovider',
            name='target_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business'), (5, 'product'), (6, 'service'), (7, 'comment')]),
        ),
        migrations.AlterField(
            model_name='serviceproviderlikeuser',
            name='actor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business')]),
        ),
        migrations.AlterField(
            model_name='serviceproviderlikeuser',
            name='target_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business'), (5, 'product'), (6, 'service'), (7, 'comment')]),
        ),
        migrations.AlterField(
            model_name='serviceproviderscoreothers',
            name='actor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business')]),
        ),
        migrations.AlterField(
            model_name='serviceproviderscoreothers',
            name='target_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'university'), (3, 'industry'), (4, 'business'), (5, 'product'), (6, 'service')]),
        ),
        migrations.AlterField(
            model_name='serviceproviderscoreserviceprovider',
            name='actor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business')]),
        ),
        migrations.AlterField(
            model_name='serviceproviderscoreserviceprovider',
            name='target_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'university'), (3, 'industry'), (4, 'business'), (5, 'product'), (6, 'service')]),
        ),
        migrations.AlterField(
            model_name='serviceprovidershareothers',
            name='actor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business')]),
        ),
        migrations.AlterField(
            model_name='serviceprovidershareothers',
            name='target_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business'), (5, 'product'), (6, 'service')]),
        ),
        migrations.AlterField(
            model_name='serviceprovidershareserviceprovider',
            name='actor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business')]),
        ),
        migrations.AlterField(
            model_name='serviceprovidershareserviceprovider',
            name='target_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business'), (5, 'product'), (6, 'service')]),
        ),
        migrations.AlterField(
            model_name='serviceprovidershareuser',
            name='actor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business')]),
        ),
        migrations.AlterField(
            model_name='serviceprovidershareuser',
            name='target_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business'), (5, 'product'), (6, 'service')]),
        ),
        migrations.AlterField(
            model_name='userlikeothers',
            name='actor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business')]),
        ),
        migrations.AlterField(
            model_name='userlikeothers',
            name='target_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business'), (5, 'product'), (6, 'service'), (7, 'comment')]),
        ),
        migrations.AlterField(
            model_name='userlikeserviceprovider',
            name='actor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business')]),
        ),
        migrations.AlterField(
            model_name='userlikeserviceprovider',
            name='target_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business'), (5, 'product'), (6, 'service'), (7, 'comment')]),
        ),
        migrations.AlterField(
            model_name='userlikeuser',
            name='actor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business')]),
        ),
        migrations.AlterField(
            model_name='userlikeuser',
            name='target_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business'), (5, 'product'), (6, 'service'), (7, 'comment')]),
        ),
        migrations.AlterField(
            model_name='userscoreothers',
            name='actor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business')]),
        ),
        migrations.AlterField(
            model_name='userscoreothers',
            name='target_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'university'), (3, 'industry'), (4, 'business'), (5, 'product'), (6, 'service')]),
        ),
        migrations.AlterField(
            model_name='userscoreserviceprovider',
            name='actor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business')]),
        ),
        migrations.AlterField(
            model_name='userscoreserviceprovider',
            name='target_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'university'), (3, 'industry'), (4, 'business'), (5, 'product'), (6, 'service')]),
        ),
        migrations.AlterField(
            model_name='usershareothers',
            name='actor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business')]),
        ),
        migrations.AlterField(
            model_name='usershareothers',
            name='target_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business'), (5, 'product'), (6, 'service')]),
        ),
        migrations.AlterField(
            model_name='usershareserviceprovider',
            name='actor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business')]),
        ),
        migrations.AlterField(
            model_name='usershareserviceprovider',
            name='target_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business'), (5, 'product'), (6, 'service')]),
        ),
        migrations.AlterField(
            model_name='usershareuser',
            name='actor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business')]),
        ),
        migrations.AlterField(
            model_name='usershareuser',
            name='target_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business'), (5, 'product'), (6, 'service')]),
        ),
    ]
