# Generated by Django 5.2.8 on 2026-07-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InteractiveOperations', '0003_alter_serviceproviderlikeothers_actor_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovidershareothers',
            name='destination_id',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business')], null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovidershareothers',
            name='platform',
            field=models.PositiveSmallIntegerField(choices=[(1, 'in site'), (2, 'telegram'), (3, 'whatsapp')], default=1),
        ),
        migrations.AlterField(
            model_name='serviceprovidershareothers',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='serviceprovidershareothers',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='serviceprovidershareserviceprovider',
            name='destination_id',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business')], null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovidershareserviceprovider',
            name='platform',
            field=models.PositiveSmallIntegerField(choices=[(1, 'in site'), (2, 'telegram'), (3, 'whatsapp')], default=1),
        ),
        migrations.AlterField(
            model_name='serviceprovidershareserviceprovider',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='serviceprovidershareserviceprovider',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='serviceprovidershareuser',
            name='destination_id',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business')], null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovidershareuser',
            name='platform',
            field=models.PositiveSmallIntegerField(choices=[(1, 'in site'), (2, 'telegram'), (3, 'whatsapp')], default=1),
        ),
        migrations.AlterField(
            model_name='serviceprovidershareuser',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='serviceprovidershareuser',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='usershareothers',
            name='destination_id',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business')], null=True),
        ),
        migrations.AlterField(
            model_name='usershareothers',
            name='platform',
            field=models.PositiveSmallIntegerField(choices=[(1, 'in site'), (2, 'telegram'), (3, 'whatsapp')], default=1),
        ),
        migrations.AlterField(
            model_name='usershareothers',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='usershareothers',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='usershareserviceprovider',
            name='destination_id',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business')], null=True),
        ),
        migrations.AlterField(
            model_name='usershareserviceprovider',
            name='platform',
            field=models.PositiveSmallIntegerField(choices=[(1, 'in site'), (2, 'telegram'), (3, 'whatsapp')], default=1),
        ),
        migrations.AlterField(
            model_name='usershareserviceprovider',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='usershareserviceprovider',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='usershareuser',
            name='destination_id',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'user'), (2, 'university'), (3, 'industry'), (4, 'business')], null=True),
        ),
        migrations.AlterField(
            model_name='usershareuser',
            name='platform',
            field=models.PositiveSmallIntegerField(choices=[(1, 'in site'), (2, 'telegram'), (3, 'whatsapp')], default=1),
        ),
        migrations.AlterField(
            model_name='usershareuser',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='usershareuser',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
