#inoMS/inoMS/settings.py
"""
Django settings for ProjectNameMS project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""



from pathlib import Path
# new_z
from typing import Dict, List, Optional
from datetime import timedelta
import os
from dotenv import load_dotenv
from django.utils.translation import gettext_lazy as _
from core.open_api import open_api_change_log
import logging


logger = logging.getLogger(__name__)  # new_z
load_dotenv()  # new_z, For development

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p55sp6grb*_bz3&ky@=@p)h=4b8=q4!2lc(#f2x3k)3=0r#s37'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ["*"]  # new_z

CORS_ORIGIN_ALLOW_ALL = True  # new_z
CORS_ALLOW_HEADERS = ["*"]  # new_z

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # ********* new_z ************
    # Project Apps
    'core',
    'ipc',
    'InteractiveOperations',
    'search',
    'system_setting',
    'report_log',
    'app_test_front',
    # add other app name ....

    'rest_framework',
    'drf_spectacular',
    'corsheaders',
    'django.contrib.postgres',
    'django_filters',

    # celery
    'django_celery_beat',

    # Django Elasticsearch integration
    'django_elasticsearch_dsl',
    # Django REST framework Elasticsearch integration (this package),
    # it provides views, serializers, filter backends, pagination and other handy add-ons
    'django_elasticsearch_dsl_drf',


     'oauth2_provider',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # ********* new_z *********************
    # for message translation
    'django.middleware.locale.LocaleMiddleware',
    "corsheaders.middleware.CorsMiddleware",

    'oauth2_provider.middleware.OAuth2TokenMiddleware',
]

ROOT_URLCONF = 'inoMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inoMS.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'Daneshjoam_Ino_MS',
        'USER': 'postgres',
        'PASSWORD': 'hahayuyu',
        'HOST': '127.0.0.1',  # or 'localhost'
        'PORT': '5432',       # this is what your error shows
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = "Asia/Tehran"  # new_z

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# //*************************** new_z ********************************************************************************

CSRF_TRUSTED_ORIGINS = ["http://localhost:8000", "http://127.0.0.1:8000"]

POSTGRES_DB_NAME = os.environ.get('POSTGRES_DB_NAME')
POSTGRES_USER = os.environ.get('POSTGRES_USER')
POSTGRES_PASSWORD = os.environ.get('POSTGRES_PASSWORD')
POSTGRES_HOST = os.environ.get('POSTGRES_HOST')
POSTGRES_PORT = os.environ.get('POSTGRES_PORT')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': POSTGRES_DB_NAME,
        'USER': POSTGRES_USER,
        'PASSWORD': POSTGRES_PASSWORD,
        'HOST': POSTGRES_HOST,
        'PORT': POSTGRES_PORT,
    }
}

ELASTICSEARCH_USER = os.environ.get('ELASTICSEARCH_USER')
ELASTICSEARCH_PASSWORD = os.environ.get('ELASTICSEARCH_PASSWORD')
ELASTICSEARCH_HOST = os.environ.get('ELASTICSEARCH_HOST')
ELASTICSEARCH_PORT = os.environ.get('ELASTICSEARCH_PORT')
ELASTICSEARCH_CA_CERTS = os.environ.get('ELASTICSEARCH_CA_CERTS')
CONNECTION_STRING = os.environ.get('CONNECTION_STRING')

ELASTICSEARCH_DSL = {
    "default": {
        "hosts": f"{ELASTICSEARCH_HOST}:{ELASTICSEARCH_PORT}",
        "http_auth": (f"{ELASTICSEARCH_USER}", f"{ELASTICSEARCH_PASSWORD}"),
        "ca_certs": f"{ELASTICSEARCH_CA_CERTS}",
        # 'verify_certs': False
    }
    # 'default': {
    #     'host': CONNECTION_STRING,
    #     'verify_certs': False
    # }
}

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "core.exception_handler.api_exception_handler",
    
    
        "DEFAULT_AUTHENTICATION_CLASSES": [
            "core.auth_tools.authentication.OAuth2BearerAuthentication",
        ],


    "DEFAULT_RENDERER_CLASSES": [
        "core.responses.CustomRenderer",
    ],
    # 'DEFAULT_FILTER_BACKENDS': [
    #     'django_filters.rest_framework.DjangoFilterBackend',
    #     # "filters.DjangoMongoEngineFilterBackend",
    # ],
}

MICROSERVICE_NAME = os.environ.get('MICROSERVICE_NAME')
SPECTACULAR_SETTINGS = {
    'TITLE': f'{MICROSERVICE_NAME} Microservice API',
    'DESCRIPTION': f"""

    {open_api_change_log.SETTING_CHANGE_LOG}

    """,
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    "EXCLUDE_PATHS": ["/schema/"],
    "SECURITY": [],
    "SECURITY_DEFINITIONS": {},
    "POSTPROCESSING_HOOKS": [
        "core.open_api.open_api_settings.custom_openapi_security_schemes",
    ],
}

FILE_UPLOAD_HANDLERS = (
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
)

# //********** for translation (i18n) *********
# mkdir locale, django-admin makemessages -l fa, django-admin makemessages -l ar, python manage.py compilemessages
# Note: add 'django.middleware.locale.LocaleMiddleware' to MIDDLEWARE
# Contains the path list where Django should look into for django.po files for all supported languages
LOCALE_PATHS = (os.path.join(BASE_DIR, 'locale'),)

LANGUAGES = [
    ('fa', _('Farsi')),
    ('en', _('English')),
    ('ar', _('Arabic')),
]
# ********** for translation (i18n) *********//

# ------------------------------ Celery ------------------------------
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND")
CELERY_ACCEPT_CONTENT = [os.environ.get("CELERY_ACCEPT_CONTENT")]
CELERY_TASK_SERIALIZER = os.environ.get("CELERY_TASK_SERIALIZER")
CELERY_RESULT_SERIALIZER = os.environ.get("CELERY_RESULT_SERIALIZER")

CELERY_BEAT_SCHEDULE = {

}

# ------------------------------ OAuth Configs ------------------------
EXCLUDE_AUTH_URLS: list[str] = ["connect"]
INCLUDE_AUTH_URLS: list[str] = []

JWT_CONFIGS: Dict = {
    "JWT_ALGORITHM": os.environ.get("JWT_ALGORITHM"),
    "PUBLIC_KEY": os.environ.get("TEMP_PUBLIC_KEY"),
    "PRIVATE_KEY": os.environ.get("TEMP_PRIVATE_KEY"),
    "SECRET_KEY": SECRET_KEY,  # PROJECT_SECRET_KEY in setting.py
    "JWT_KWARGS": {
        "JWT_AUDIENCE": os.environ.get("CLIENT_ID"),
        "JWT_ISSUER": os.environ.get("JWT_ISSUER"),
    },
}
